[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "london"
via_ir = false
fuzz = { runs = 256 }
invariant = { runs = 256 }

[rpc_endpoints]
mezotestnet = "https://rpc.test.mezo.org"
mezomainnet = "${MAINNET_RPC_URL}"

[etherscan]
mezotestnet = { key = "not-required", url = "https://explorer.test.mezo.org/api" }
mezomainnet = { key = "not-required", url = "https://explorer.mezo.org/api" }
